### ISSUE TITLE
테스트 환경 구축

### ISSUE THREAD

**Issue by onetuks** [Guzzing/Studay_Server#137]
- 테스트 코드 내 Mock 제거
- 테스트 별 컴포넌트 스캔 범위 설정
- DB 종속 제거 방법 고안

**Comment by onetuks** [comment]
- [x] 별 작업 완료
- [ ] 원우 작업 완료
- [x] 세영 작업 완료

**Comment by wonu606** [comment]
ㄹㅇㅇ
